name: flutter_x
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # 汉字转拼音库 https://github.com/flutterchina/lpinyin
  lpinyin: ^1.0.7
  # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  common_utils: ^1.1.1
  shared_preferences: ^0.5.1
  cached_network_image: ^0.8.0
  pull_to_refresh: 1.1.6
#  webview_flutter: ^0.3.10
#  flutter_webview_plugin: ^0.3.5
#  可以实现组合布
#  flutter_inappbrowser: ^1.2.1
  flutter_html: ^0.9.6
  azlistview: ^0.1.1
  flustars: ^0.2.5+1
  flutter_swiper: ^1.0.6
  flukit: ^1.0.0
  path_provider: ^0.5.0+1
  dio: ^2.1.13
  url_launcher: ^5.0.2
  #  用于在Android和iOS上与其他Flutter窗口小部件一起显示内嵌视频。
  video_player: ^0.10.1+4
#  flutter_html_textview: ^0.2.6
  #  将html呈现为一个Widget,在textview中呈现html
#  flutter_html_view: ^0.5.11
  #  SQLite的Flutter插件，一个自包含的高可靠性嵌入式SQL数据库引擎。
#  sqflite: ^1.1.6+1
  #时间，日期时间，icon，自定义数据的选择器，可以居中弹窗
#  flutter_picker: ^1.0.13
  #  创建Notifications
  local_notifications: ^0.0.7
# git 库
#  flutter_fai_webview:
#    git:
#      url: https://github.com/zhaolongs/Flutter_Fai_Webview.git
#      ref: master

#本地库
  flutter_fai_webview:
    path: /Users/androidlongs/Desktop/code/flutter_app/flutter_fai_webview/flutter_fai_webview

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - images/ic_nav_news_normal.png
    - images/ic_nav_news_actived.png
    - images/ic_nav_tweet_normal.png
    - images/ic_nav_tweet_actived.png
    - images/ic_nav_discover_normal.png
    - images/ic_nav_discover_actived.png
    - images/ic_nav_my_normal.png
    - images/ic_nav_my_pressed.png
    - images/bg_person_header.png
    - images/icon_setting.png
    - images/default_banner.jpg
    - images/ic_test.png
    - images/flutter_x_icon.png
    - images/phone_select_icon.png
    - images/phone_noselect_icon.png